name: Deploy Cloudflare

on:
  push:
    branches:
      - main
      - dev
    paths:
      - cloudflare/**
      - .github/workflows/cloudflare.yml

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.CLOUDFLARE_D1_DATABASE_ID }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Node Setup
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Deploy Cloudflare application and D1
        run: ./cloudflare/deploy/deploy.sh